/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import java.awt.Image;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.CellEditor;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Pantalla3 extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla3
     */
    inicioframe casa;
    int opcionradiobuttion = 0;
    DBConexion miconexionp3 = new DBConexion();
    ArrayList<Region> regiones = new ArrayList<>();

    public Pantalla3() {
        initComponents();
        this.setLocationRelativeTo(null);

        int camiones;
        float distancia;
        float ctransporte;
        float coperacion;
        float cmantenimiento;
        float cfinanciero;
        float vdigestato;
        float venergia;
        float eproducida;
        float pproducida;
        float voldigestor;
        float bgproducido;
        String nregion;

        ResultSet consultaregiones = miconexionp3.getQuery("SELECT * FROM casoestudio");

        try {
            while (consultaregiones.next()) {

                nregion = consultaregiones.getString("nombre_region");
                bgproducido = consultaregiones.getFloat("biogas_producido");
                voldigestor = consultaregiones.getFloat("volumen_digestor");
                pproducida = consultaregiones.getFloat("potencia_producida");
                eproducida = consultaregiones.getFloat("energia_producida");
                venergia = consultaregiones.getFloat("venta_energia");
                vdigestato = consultaregiones.getFloat("venta_digestato");
                cfinanciero = consultaregiones.getFloat("costo_financiero");
                cmantenimiento = consultaregiones.getFloat("costo_mantenimiento");
                coperacion = consultaregiones.getFloat("costo_operacion");
                ctransporte = consultaregiones.getFloat("costo_transporte");
                distancia = consultaregiones.getFloat("distancia");
                camiones = consultaregiones.getInt("camiones_requeridos");

                Region R = new Region(nregion, bgproducido, voldigestor, pproducida, eproducida, venergia, vdigestato, cfinanciero, cmantenimiento, coperacion, ctransporte, distancia, camiones);

                regiones.add(R);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla3.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGpRegiones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        RbtnRegion1 = new javax.swing.JRadioButton();
        RbtnRegion2 = new javax.swing.JRadioButton();
        RbtnRegion3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldimensionamiento = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcostos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblinfotransporte = new javax.swing.JTable();
        lblgraficaprincipal = new javax.swing.JLabel();
        BtnGraficar = new javax.swing.JButton();
        BtnVerRegion = new javax.swing.JButton();
        home = new javax.swing.JButton();
        reload = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        autores = new javax.swing.JLabel();
        Imagenfondo_pantalla1 = new javax.swing.JLabel();

        BtnGpRegiones.add(RbtnRegion1);
        BtnGpRegiones.add(RbtnRegion2);
        BtnGpRegiones.add(RbtnRegion3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Green Biogas");
        setMinimumSize(new java.awt.Dimension(1366, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnGpRegiones.add(RbtnRegion1);
        RbtnRegion1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        RbtnRegion1.setText("Region 1");
        RbtnRegion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegion1ActionPerformed(evt);
            }
        });
        jPanel1.add(RbtnRegion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        BtnGpRegiones.add(RbtnRegion2);
        RbtnRegion2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        RbtnRegion2.setText("Region 2");
        RbtnRegion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegion2ActionPerformed(evt);
            }
        });
        jPanel1.add(RbtnRegion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, -1));

        BtnGpRegiones.add(RbtnRegion3);
        RbtnRegion3.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        RbtnRegion3.setText("Region 3");
        RbtnRegion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnRegion3ActionPerformed(evt);
            }
        });
        jPanel1.add(RbtnRegion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 100, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 50, 410, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIMENSIONAMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 24))); // NOI18N
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbldimensionamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbldimensionamiento);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 80));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(800, 180, 520, 130);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COSTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 24))); // NOI18N
        jPanel3.setAutoscrolls(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblcostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblcostos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 550, 70));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(760, 320, 570, 130);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION TRANSPORTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 3, 24))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblinfotransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblinfotransporte);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 70));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(820, 480, 500, 120);

        lblgraficaprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplicacion/REGIONES_1.jpg"))); // NOI18N
        lblgraficaprincipal.setText("MAPA REGIONES");
        lblgraficaprincipal.setToolTipText("");
        lblgraficaprincipal.setDoubleBuffered(true);
        getContentPane().add(lblgraficaprincipal);
        lblgraficaprincipal.setBounds(10, 110, 750, 630);

        BtnGraficar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        BtnGraficar.setText("Graficar");
        BtnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGraficar);
        BtnGraficar.setBounds(1120, 650, 120, 25);

        BtnVerRegion.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        BtnVerRegion.setText("Ver Region");
        BtnVerRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerRegionActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVerRegion);
        BtnVerRegion.setBounds(820, 650, 140, 25);

        home.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplicacion/Imagen.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(10, 10, 40, 40);

        reload.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplicacion/Imagen1.png"))); // NOI18N
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        getContentPane().add(reload);
        reload.setBounds(1190, 20, 40, 40);

        jButton1.setText("OBTENER DATOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(990, 100, 130, 23);

        autores.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        autores.setText("Creadores: Daniel Esteban Martinez, Jean Paul  Cholo - Universidad EAN");
        getContentPane().add(autores);
        autores.setBounds(750, 30, 350, 14);

        Imagenfondo_pantalla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplicacion/large.jpg"))); // NOI18N
        Imagenfondo_pantalla1.setDoubleBuffered(true);
        Imagenfondo_pantalla1.setMaximumSize(new java.awt.Dimension(1280, 800));
        Imagenfondo_pantalla1.setMinimumSize(new java.awt.Dimension(1280, 800));
        Imagenfondo_pantalla1.setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().add(Imagenfondo_pantalla1);
        Imagenfondo_pantalla1.setBounds(0, 0, 1340, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbtnRegion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegion1ActionPerformed

       
    }//GEN-LAST:event_RbtnRegion1ActionPerformed

    private void RbtnRegion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegion2ActionPerformed


    }//GEN-LAST:event_RbtnRegion2ActionPerformed

    private void RbtnRegion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnRegion3ActionPerformed


    }//GEN-LAST:event_RbtnRegion3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        DefaultTableModel Modelo1 = (DefaultTableModel) tbldimensionamiento.getModel();

        Modelo1.addColumn("Biogas producido");
        Modelo1.addColumn("Volumen Digestor");
        Modelo1.addColumn("Potencia Producida");
        Modelo1.addColumn("Energia producida");

        DefaultTableModel Modelo2 = (DefaultTableModel) tblcostos.getModel();

        Modelo2.addColumn("Venta energia");
        Modelo2.addColumn("Venta digestato");
        Modelo2.addColumn("Mantenimiento");
        Modelo2.addColumn("Operacion");
        Modelo2.addColumn("Financiacion");
        Modelo2.addColumn("Tranporte");

        DefaultTableModel modelo3 = (DefaultTableModel) tblinfotransporte.getModel();

        modelo3.addColumn("Camiones requeridos");
        modelo3.addColumn("Distancia Recorrida");

        //ImageIcon FondoFrame = new ImageIcon("src/Aplicacion/Large.jpg");
        //Icon iconoFondo = new ImageIcon(FondoFrame.getImage().getScaledInstance(Imagenfondo_pantalla1.getWidth(), Imagenfondo_pantalla1.getHeight(), Image.SCALE_DEFAULT));
        //Imagenfondo_pantalla1.setIcon(iconoFondo);
       
        
        //ImageIcon imagen = new ImageIcon("src/Aplicacion/Regiones.jpg");
        //Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblgraficaprincipal.getWidth(), lblgraficaprincipal.getHeight(), Image.SCALE_DEFAULT));
        //lblgraficaprincipal.setIcon(icono);

        
       this.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void BtnVerRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerRegionActionPerformed

        if (RbtnRegion1.isSelected()) {
            opcionradiobuttion = 1;
        } else if (RbtnRegion2.isSelected()) {
            opcionradiobuttion = 2;
        } else {
            opcionradiobuttion = 3;
        }


        Regiones Grafica1 = new Regiones(opcionradiobuttion);

    }//GEN-LAST:event_BtnVerRegionActionPerformed

    private void BtnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraficarActionPerformed

        //opcionradiobuttion=BtnGpRegiones.getSelection();
        if (RbtnRegion1.isSelected()) {
            opcionradiobuttion = 1;
        } else if (RbtnRegion2.isSelected()) {
            opcionradiobuttion = 2;
        } else {
            opcionradiobuttion = 3;
        }

        GraficasCasoestudio Grafica2 = new GraficasCasoestudio(opcionradiobuttion);
    }//GEN-LAST:event_BtnGraficarActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        dispose();
        casa = new inicioframe();
        casa.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        dispose();
        Pantalla3 P3 = null;

        P3 = new Pantalla3();

        P3.setVisible(true);
    }//GEN-LAST:event_reloadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Region R;
        
        if(RbtnRegion1.isSelected()){
            
            R=regiones.get(0);
        }
        else if(RbtnRegion2.isSelected()){
            
            R=regiones.get(1);
        }
        else {
                R=regiones.get(2);
                }
        
        R.biogasproducido = redondeara2(R.biogasproducido);
        tbldimensionamiento.setValueAt(R.biogasproducido, 0, 0);
        R.volumendigestor = redondeara2(R.volumendigestor);
        tbldimensionamiento.setValueAt(R.volumendigestor, 0, 1);
        R.potenciaproducida = redondeara2(R.potenciaproducida);        
        tbldimensionamiento.setValueAt(R.potenciaproducida, 0, 2);
        R.energiaproducida = redondeara2(R.energiaproducida);        
        tbldimensionamiento.setValueAt(R.energiaproducida, 0, 3);
        
        R.ventaenergia = redondeara2(R.ventaenergia);
        tblcostos.setValueAt(R.ventaenergia, 0, 0);
        R.ventadigestato = redondeara2(R.ventadigestato);        
        tblcostos.setValueAt(R.ventadigestato, 0, 1);
        R.costomantenimiento = redondeara2(R.costomantenimiento);        
        tblcostos.setValueAt(R.costomantenimiento, 0, 2);
        R.costooperacion = redondeara2(R.costooperacion);        
        tblcostos.setValueAt(R.costooperacion, 0, 3);
        R.costofinanciero = redondeara2(R.costofinanciero);        
        tblcostos.setValueAt(R.costofinanciero, 0, 4);
        R.costotransporte = redondeara2(R.costotransporte);
        tblcostos.setValueAt(R.costotransporte, 0, 5);

        tblinfotransporte.setValueAt(R.camiones, 0, 0);
        tblinfotransporte.setValueAt(R.distancia, 0, 1);
        
        
        
    
    
    
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private double redondeara2(double numero) {
        String val = numero + "";
        BigDecimal big = new BigDecimal(val);
        big = big.setScale(2, RoundingMode.HALF_UP);
        double redondeo = big.doubleValue();
        return redondeo;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGpRegiones;
    private javax.swing.JButton BtnGraficar;
    private javax.swing.JButton BtnVerRegion;
    private javax.swing.JLabel Imagenfondo_pantalla1;
    private javax.swing.JRadioButton RbtnRegion1;
    private javax.swing.JRadioButton RbtnRegion2;
    private javax.swing.JRadioButton RbtnRegion3;
    private javax.swing.JLabel autores;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblgraficaprincipal;
    private javax.swing.JButton reload;
    private javax.swing.JTable tblcostos;
    private javax.swing.JTable tbldimensionamiento;
    private javax.swing.JTable tblinfotransporte;
    // End of variables declaration//GEN-END:variables
}
